name: build,test and package action
description: Test action for dotnet application

inputs:
  path:  # id of input
    description: 'path to project file'
    required: true
    default: './'

runs:
  using: 'composite'       
  steps:
  
    - name: Restore dependencies
      run: dotnet restore ${{inputs.path}}
      shell: bash
      
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore
      shell: bash
      
    - name: test with dotnet
      run: dotnet test --no-build --verbosity normal
      shell: bash

    - name: package
      run: dotnet pack --no-build -c Release
      shell: bash
