name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}  # Dynamically set the OS
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Define the operating systems
        node-version: [14, 16]           # Define the Node.js versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
