name: Node.js CI

on:
  workflow_call:  # This enables the workflow to be reusable
    inputs:
      node-versions:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest  # Use the input OS variable
    strategy:
      matrix:
        index: [0,1]
        include:
        - node-version: ${{ fromJson(inputs.node-versions)[matrix.index] }} # Use the input Node versions
          os-version: ${{ fromJson(inputs.os)[matrix.index] }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: print os
      run: echo "${{ matrix.os-version }}"
