name: Node.js CI

on:
  workflow_call:  # This enables the workflow to be reusable
    inputs:
      node-version:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest  # Use the input OS variable
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node-version) }}
        os-version: ${{ fromJson(inputs.os) }} # Use the input Node versions
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: display os
      run: echo "${{ matrix.os-version }}"


  display:
    runs-on: ubuntu-latest  # Use the input OS variable
    needs: build
    strategy:
      matrix:
          os-version: ${{ fromJson(inputs.os) }}
    steps:
    - name: print os
      run: echo "${{ matrix.os-version }}"

    - name: print node
      run: echo "${{ matrix.node-version }}"
