name: Node.js CI

on:
  workflow_call:  # This enables the workflow to be reusable
      # inputs:
      # node-version:
      #   required: true
      #   type: string
      # os:
      #   required: true
      #   type: string
      inputs:
        combinations:
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest  # Use the input OS variable
    strategy:
      matrix:
        include: ${{ fromJson(inputs.combinations) }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: display os
      run: echo "${{ matrix.os-version }}"

  display:
    runs-on: ubuntu-latest  # Use the input OS variable
    needs: build
    steps:
    - name: print os
      run: echo "${{ matrix.os-version }}"
